### PR TITLE
Add data handling functionality for XNAT

### PR DESCRIPTION
**Pull request by sophie22**
### Summary of changes
Move the functions related to XNAT data handling from MLOps package into the project template.

### Reason for changes
Data handling functionality is not applicable for all ML projects developed through MLOps, but may be a useful template when creating/training new image analysis models, therefor base functions for XNAT data handling are more suitable to be in this repo.

## Quality Assurance
- [x] Unit tests added

---
- [x] Reviewed and approved by an authorised Quality Representative.

### CODE REVIEW

**Review by mikewoodward94 — APPROVED** [review]
Looks good to me!

Thank you for making these changes, especially making the readme more readable!

**Review by tomaroberts — COMMENTED** [review]
Also looks good to me.

~~Is the intention to update the MLOps repo as well to reflect the changes ported across to here? My only concern there is if that breaks/causes issues to anything with projects that use the MLOps code in its current form.~~

Edit: can see it was implemented [here](https://github.com/GSTT-CSC/MLOps/pull/171). Assuming no issues with MLOps projects, then go ahead.

**Review by tomaroberts — CHANGES_REQUESTED** [review]
I've just encountered these changes with the files being moved from the MLOps repo breaking one of my builds. The changes are fine, but we need to be mindful that other people may encounter the same issue if they use a newer version of MLOps and the files are missing.

One change request: `tools.py` is in the transforms folder. I think it should be `utils/tools.py` instead. The transforms folder is intended to house custom MONAI Transforms. The functions in tools.py use Transforms but are not Transforms themselves.

**Review by tomaroberts — APPROVED** [review]
Thanks Sophie

**Pull request merged**
